# Generated by Django 3.2.6 on 2021-08-11 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
            ],
            options={
                'verbose_name': 'city',
            },
        ),
        migrations.CreateModel(
            name='SubscribedCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subscribed_city',
            },
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='weather_cit_name_db5943_idx'),
        ),
    ]
