# Generated by Django 3.2.6 on 2021-08-13 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_subscribedcity_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('main', models.CharField(blank=True, max_length=256)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('temp', models.FloatField(blank=True)),
                ('temp_min', models.FloatField(blank=True)),
                ('temp_max', models.FloatField(blank=True)),
                ('pressure', models.FloatField(blank=True)),
                ('humidity', models.FloatField(blank=True)),
                ('wind_speed', models.FloatField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='weather.city')),
            ],
            options={
                'verbose_name': 'weather',
            },
        ),
    ]
