# Generated by Django 3.2.6 on 2021-08-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_weather_city_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='city_name',
            new_name='name',
        ),
    ]
