# Generated by Django 3.2.6 on 2021-08-13 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_rename_city_name_weather_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='city',
            new_name='city_id',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='name',
            new_name='city_name',
        ),
    ]
