# Generated by Django 3.2.6 on 2021-08-13 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_auto_20210813_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='city_id',
            field=models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.PROTECT, to='weather.city'),
        ),
    ]
