# Generated by Django 3.2.6 on 2021-08-16 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_alter_weather_city_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribedcity',
            name='last_run_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
